### ISSUE TITLE
Computation failed in `stat_wireframe()`: object 'x' not found

### ISSUE THREAD

**Issue by NB-Bio** [AckerDWM/gg3D#6]
Hi and thank you for the package, 
I'm having an issue with a wireframe plot. 
I'm using your vignette as a guideline: 

`ggplot(df, aes(Var1, Var2, z=value)) +
  axes_3D() +
  stat_wireframe(alpha=.5) +
  theme_void() +
  theme(legend.position = "none") +
  labs_3D(hjust=c(0,1,1), vjust=c(1, 1, -0.2), angle=c(0, 0, 90))`

When adapting the code to my case, I write:
`ggplot(df, aes(Dim1, Dim2, z = Dim3)) + axes_3D() + stat_wireframe(alpha=.5) + theme_void() 
`
where `df` is my dataframe with three columns called "Dim1, Dim2, "Dim3".
However, I obtain the messag

**Warning message:
Computation failed in `stat_wireframe()`:
object 'x' not found**

and an empty 3D space (only the 3 axes)

I don't understand which is the problem. Could you help me?

Thank you

**Comment by AckerDWM** [comment]
Hard to say without seeing the dataframe. Can you show the output of str(df)?

Daniel Acker, PhD

**Comment by EvanJo** [comment]
When using data tables instead of data frames, stat_wireframe produces an empty plot with the following warning message:

Computation failed in stat_wireframe():
object 'x' not found

Solution: Make sure the data is actually data frame.

**Comment by EvanJo** [comment]
I encountered the same issue. The data was passed in as a data table. Wrapping your table with `df=as.data.frame(dt)` worked for me.

P.S.: @AckerDWM Thanks for the great package. This was EXACTLY what I was looking for, as it works beautifully when generating tikz plots for latex.

**Comment by lenarddome** [comment]
> When using data tables instead of data frames, stat_wireframe produces an empty plot with the following warning message:
> 
> Computation failed in stat_wireframe():
> object 'x' not found
> 
> Solution: Make sure the data is actually data frame.

I think I found the cause. I opened am issue with a slightly different warning coming from `stat_wireframe`. It seems that if I load dplyr, both this issue and #9 is resolved.

**Comment by py9mrg** [comment]
I'm not sure this issue should be closed if loading dplyr is the fix. That means there's one or more missing `dplyr::` in the gg3D code, and those need to be fixed.
